### ISSUE TITLE
Using $var to distinguish between vars?

### ISSUE THREAD

**Issue by oschulz** [joshday/PropertyUtils.jl#1]
Nice package idea, @joshday ! I was playing with a similar concept not too long ago and thought about how to cleanly separate "property" variables from "external" ones.

Just an idea: What do you think about using something like

```julia
z = 3
result = @with (x = 1, y = 2) begin 
    $x + $y + z
end
```

A bit less concise, but it wouldn't need `hasproperty`, which may become a source of type instability with types that specialize `propertynames`. Or maybe a second macro in addition to `with` that used `$var`?

**Comment by joshday** [comment]
I like the idea of using the string interpolation syntax, especially for more complicated code blocks.  However, I also like how super-simple the current macro is.

I think a second macro/using dispatch would be a good idea.  

- `@with_interp`?  
- Choose your own interpolation identifier through dispatch?:

```Julia
z = 3
result = @with :$ (x = 1, y = 2) begin 
    $x + $y + z
end
result = @with :(:) (x = 1, y = 2) begin 
    :x + :y + z
end
```

**Comment by oschulz** [comment]
I also have an implementation of a macro that does broadcasting on properties (for easy column-wise ops on tables, etc.). I've been thinking of creating a small package for it, but maybe it would fit into PropertyUtils?

**Comment by oschulz** [comment]
It's a simple macro called `@bfp` ("broadcast function over properties", wanted something short, maybe not the best name). Given something with vector/column-like properties `a`, `b`, `c` it allows you to do this

```julia
data[@bfp $a * $b + $c < 0.25]
```

As an equivalent for this

```julia
data[data.a .* data.b .+ data.c .< 0.25]
```

Very quick to write, but a *lot* faster than Query.jl, etc., esp. if only some of the columns of `data` are accessed.

**Comment by oschulz** [comment]
If you think broadcasted property access would fit in here, I could put together a WIP PR, and we could see where it might lead. But I can also make a separate package if you'd like to keep PropertyUtils more lightweight.

**Comment by joshday** [comment]
Also I just tried this and it works out of the box:

```Julia
@. @with df df[a * b * c < .25, :]

@with df @. df[a * b * c < .25, :]
```

Would your macro provide a benefit above composing `@with` with `@.`?  There did seem to be a lot of JIT overhead on the first run

**Comment by oschulz** [comment]
Hm, maybe. The way this works is a bit different: `@bfp $a * $b + $c < 0.25` creates a function that will take some data, and then run the broadcast. And I specialize a few operations like `getindex`, `filter`, etc., to make things more concise. So
`data[@bfp $a * $b + $c < 0.25]` is actually a shortcut for `data[(@bfp $a * $b + $c < 0.25)(data)]`.

Regarding code-gen, I guess what I currently do will be more lightweight, because the broadcast directly gets a ready-made single function.

A big difference is that with `@bfp`, the function is *only* broadcast over the properties, so external variables don't have to be wrapped in a `Ref`, and in fact *can't* be broadcast over (by design). I guess this is really something where only a variant that has the vars prefixed with `$` makes sense, otherwise the behavior would be unpredictable for somebody reading the code.

**Comment by oschulz** [comment]
Another difference is that `@with df @. a * b * c < .25` will usually instantiate the `NamedTuple` for each full row of `df` (I think I've seen the compiler elide it with TypedTables in very simple cases, but often, it can't).

`(@bfp $a * $b + $c < .25)(df)` on the other hand, build's a a function `f(a, b, c)` and broadcasts over `df.a`, `df.b` and `df.c` and never touches any other columns of `df` - so that memory is never accessed. That can make a big difference, cache- and bandwidth-wise sometimes.

**Comment by oschulz** [comment]
There could, of course, also be a non-broadcast version of `@bfp` - say, `@propfunc`. So I guess one could have

* `@with obj expr` that takes an object and expression - since the object is available, it's properties are known and prop-access in `expr` doesn't need to be `$`-prefixed. Having a broadcasted variant might be useful (to optimize mem-access, etc.). 

* `(@propfunc expr)(obj)` that takes an expression and builds a function that can then be applied to any object (that has the right properties). Since the `obj` isn't known yet, prop-access in `expr` needs to be `$`-prefixed, to mark which vars should access properties (otherwise, behaviour would seem unpredictable). But the result of `(@propfunc expr)` can be passed around, etc. `@bfp` (or similar) would the variant that creates a function that broadcasts over the data.

I think both approaches could be very useful at times. Question is just if they should live in the same package. :-) But maybe it would be nice to have central package to deal with such issues. We have bit and pieces like this scattered across the ecosystem I think, we could (humbly try to) establish some kind of standard set of operations to provide convenient prop-access.

**Comment by joshday** [comment]
> Another difference is that `@with df @. a * b * c < .25` will usually instantiate the NamedTuple for each full row of `df` 

I don't think that's correct, since we are operating on columns instead of rows: `@.` gives the functions dots and then `@with` pulls out the 3 columns needed.

---

My gut intuition is that `@bfp` is too "magical", but if it does indeed provide a benefit over composing `@.` and `@with`, it would be nice to have here.

**Comment by oschulz** [comment]
> @. gives the functions dots and then @with pulls out the 3 columns needed.

Ah, you're, right of course! Maybe something like @bfp will still be convenient for `filterby`, etc. (esp. for quick interactive use), but I probably should flesh this out a bit more.

**Comment by clarkevans** [comment]
@oschulz For what it's worth, I kinda like `(@propfunc expr)` idea.  Copying the data isn't great, it'd be better to have a function that can be broadcasted.

**Comment by oschulz** [comment]
Hey @joshday , just came back to this (after a long time :-) ) - nowadays (PropertyUtils v1.3, Julia v1.9), this still works

```julia
julia> df = @inferred StructArray(
    a = rand(100), b = rand(100),
    c = rand(100), d = rand(100),
    e = rand(100), f = rand(100)
)

julia> @. @with df df[a * c * d < .25, :]
```

But this one doesn't anymore

```julia
julia> @with df @. df[a * c * d < .25, :]
ERROR: UndefVarError: `##337` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[36]:1
```

Any idea why? The second version is the one that avoids reading all columns and instantiating whole `NamedTuple{(:a, :b, :c, :d, :e, :f)}` entries, right?

**Comment by oschulz** [comment]
For future reference, I've created [PropertyFunctions.jl](https://github.com/oschulz/PropertyFunctions.jl) to explore the concept of `$var` referencing properties.
